### ISSUE TITLE
ppg freeze fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by johnosbb** [runesc/PPG#4]
ppg freeze

Traceback (most recent call last):
  File "/home/johnos/anaconda3/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/__main__.py", line 126, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 815, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 762, in build
    exec(code, spec_namespace)
  File "/home/johnos/Lyrical/ProtoTyping/ButtonResize/target/PyInstaller/testapp.spec", line 7, in <module>
    a = Analysis(['/home/johnos/Lyrical/ProtoTyping/ButtonResize/src/main/python/main.py'],
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 294, in __init__
    self.__postinit__()
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/building/datastruct.py", line 159, in __postinit__
    self.assemble()
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 473, in assemble
    self.graph.process_post_graph_hooks(self)
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/depend/analysis.py", line 373, in process_post_graph_hooks
    module_hook.post_graph(analysis)
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/depend/imphook.py", line 451, in post_graph
    self._load_hook_module()
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/depend/imphook.py", line 408, in _load_hook_module
    self._hook_module = importlib_load_source(
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/compat.py", line 632, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1029, in load_module
  File "<frozen importlib._bootstrap_external>", line 854, in load_module
  File "<frozen importlib._bootstrap>", line 274, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/hooks/hook-PyQt5.QtGui.py", line 11, in <module>
    from PyInstaller.utils.hooks.qt import add_qt5_dependencies
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/utils/hooks/qt.py", line 163, in <module>
    pyqt6_library_info = QtLibraryInfo('PyQt6')
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/utils/hooks/qt.py", line 61, in __init__
    if hooks.is_module_satisfies("PyQt6 >= 6.0.3"):
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/PyInstaller/utils/hooks/__init__.py", line 482, in is_module_satisfies
    pkg_resources.get_distribution(requirements)
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 514, in get_distribution
    dist = get_provider(dist)
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 386, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 956, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 815, in resolve
    dist = self._resolve_dist(
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 844, in _resolve_dist
    env = Environment(self.entries)
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2640, in hashcmp
    self.parsed_version,
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2694, in parsed_version
    raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '4.0.0-unsupported' (package: pyodbc)
Traceback (most recent call last):
  File "/home/johnos/anaconda3/bin/ppg", line 8, in <module>
    sys.exit(_main())
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/ppg/__main__.py", line 17, in _main
    ppg.cmdline.main()
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/ppg/cmdline.py", line 32, in main
    fn(*args)
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/ppg/builtin_commands/__init__.py", line 178, in freeze
    freeze_ubuntu(debug=debug)
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/ppg/freeze/ubuntu.py", line 4, in freeze_ubuntu
    freeze_linux(debug)
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/ppg/freeze/linux.py", line 8, in freeze_linux
    run_pyinstaller(debug=debug)
  File "/home/johnos/anaconda3/lib/python3.9/site-packages/ppg/freeze/__init__.py", line 48, in run_pyinstaller
    run(args, check=True)
  File "/home/johnos/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pyinstaller', '--name', 'testapp', '--noupx', '--log-level', 'ERROR', '--noconfirm', '--distpath', '/home/johnos/Lyrical/ProtoTyping/ButtonResize/target', '--specpath', '/home/johnos/Lyrical/ProtoTyping/ButtonResize/target/PyInstaller', '--workpath', '/home/johnos/Lyrical/ProtoTyping/ButtonResize/target/PyInstaller', '--additional-hooks-dir', '/home/johnos/anaconda3/lib/python3.9/site-packages/ppg/freeze/hooks', '--runtime-hook', '/home/johnos/Lyrical/ProtoTyping/ButtonResize/target/PyInstaller/fbs_pyinstaller_hook.py', '/home/johnos/Lyrical/ProtoTyping/ButtonResize/src/main/python/main.py']' returned non-zero exit status 1.

**Comment by johnosbb** [comment]
Compatibility issue with pyobdc, so:
pip install -U pyodbc

**Comment by runesc** [comment]
Hi @johnosbb 

Thank you for reporting this issue. Freezing errors are often related to problems with PyInstaller hooks. I recommend trying using a higher version of PyInstaller or creating a custom hook.

In the update that will be released next week, I will be using PyInstaller version 6.9.0, which likely handle this issue. Additionally, I suggest adding your dependency to the "hidden_imports" section in the `src/build/settings/base.json` file. Here's an example:

![image](https://github.com/user-attachments/assets/818e2169-a137-40f5-8d9c-630a33ef85e3)

This should help PyInstaller handle the dependencies correctly.

I hope this resolves the issue! Please let us know if you need further assistance.
