### ISSUE TITLE
Error on launching application

### ISSUE THREAD

**Issue by johnosbb** [runesc/PPG#5]
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "ppg_runtime/application_context/PyQt5.py", line 24, in <module>
ImportError: /home/johnos/Lyrical/ProtoTyping/ButtonResize/target/testapp/libQt5Core.so.5: version `Qt_5.15' not found (required by /home/johnos/Lyrical/ProtoTyping/ButtonResize/target/testapp/PyQt5/QtGui.abi3.so)
[1036679] Failed to execute script 'main' due to unhandled exception!

**Comment by runesc** [comment]
Hi @johnosbb 

It seems that PyInstaller is trying to load the wrong version of PyQt. You likely have multiple versions installed. I suggest checking your versions with pip show PyQt5, uninstalling any extra versions if necessary, and cleaning up any previous builds before recompiling. This should resolve the version conflict.
